<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktyvus',
    'Are you sure you want to delete this user?' => 'Ar tikrai norite pašalinti šį vartotoją?',
    'Banned' => 'Blokuotas',
    'Bind to IP' => 'Pririšti prie IP adreso',
    'Browser' => 'Naršyklė',
    'Change own password' => 'Keisti savo slaptažodį',
    'Change password' => 'Keisti slaptažodį',
    'Changing password' => 'Slaptažodžio keitimas',
    'Changing password for user: ' => 'Keičiamas vartotojo slaptažodis: ',
    'Child permissions' => '',
    'Child roles' => '',
    'Code' => 'Kodas',
    'Confirmation Token' => 'Patvirtinimo kodas',
    'Create' => 'Sukurti',
    'Created' => 'Sukurta',
    'Creating permission group' => '',
    'Current password' => 'Dabartinis slaptažodis',
    'Data' => 'Duomenys',
    'Delete' => 'Trinti',
    'Description' => 'Aprašymas',
    'E-mail' => 'El. paštas',
    'E-mail confirmed' => 'El. paštas patvirtintas',
    'E-mail with activation link has been sent to <b>{email}</b>. This link will expire in {minutes} min.' => 'El. pašto patvirtinimo nuoroda buvo išsiųsta <b>{email}</b> adresu. Šios nuorodos galiojimas baigsis po {minutes} min.',
    'Edit' => 'Redaguoti',
    'Editing' => 'Redagavimas',
    'Editing permission group' => '',
    'Editing permission: ' => '',
    'Editing role: ' => '',
    'Editing user: ' => '',
    'For example: 123.34.56.78, 168.111.192.12' => 'Pvz.: 123.34.56.78, 168.111.192.12',
    'Group' => 'Grupė',
    'ID' => '',
    'IP' => '',
    'Inactive' => 'Neaktyvus',
    'Language' => 'Kalba',
    'Login' => 'Prisijungti',
    'Name' => 'Pavadinimas',
    'OS' => '',
    'Password' => 'Slaptažodis',
    'Password has been changed' => 'Slaptažodis pakeistas',
    'Permission creation' => '',
    'Permission groups' => '',
    'Permissions' => '',
    'Permissions for role:' => '',
    'Refresh routes' => 'Atnaujinti',
    'Refresh routes (and delete unused)' => 'Atnaujinti (ištrinant nenaudojamus)',
    'Registration IP' => 'Registracijos IP',
    'Repeat password' => 'Pakartokite slaptažodį',
    'Reset' => '',
    'Role creation' => '',
    'Roles' => '',
    'Roles and permissions' => '',
    'Roles and permissions for user:' => '',
    'Routes that are not exists in this application will be deleted. Do not recommended for application with "advanced" structure, because frontend and backend have they own set of routes.' => '',
    'Rule' => '',
    'Save' => 'Saugoti',
    'Saved' => 'Išsaugota',
    'Search' => 'Paieška',
    'Search route' => 'Ieškoti kelio',
    'Settings for permission' => '',
    'Show all' => 'Rodyti visus',
    'Show only selected' => 'Rodyti tik pažymėtus',
    'Status' => 'Būsena',
    'Superadmin' => '',
    'Token' => '',
    'Too many attempts' => 'Per daug bandymų',
    'Type' => 'Tipas',
    'Updated' => 'Redaguota',
    'User' => 'Vartotojas',
    'User agent' => '',
    'User creation' => 'Vartotojo sukūrimas',
    'Users' => 'Vartotojai',
    'Visit Time' => 'Apsilankymo laikas',
    'Visit log' => 'Apsilankymų žurnalas',
    'Wrong format. Enter valid IPs separated by comma' => 'Neteisingas formatas. Įveskite IP adresus atskirtus kableliais.',
    'Wrong password' => 'Neteisingas slaptažodis',
    'You can not change own permissions' => 'Negalite keisti savo paties teisių',
];
