<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authorization' => 'Autorizacija',
    'Captcha' => '',
    'Check your E-mail for further instructions' => 'Patikrinkite savo el. paštą dėl tolesnių nurodymų',
    'Check your e-mail {email} for instructions to activate account' => 'Patikrinkite savo {email} el. paštą dėl tolesnių nurodymų kaip aktyvuoti paskyrą',
    'Confirm' => 'Patvirtinti',
    'Confirm E-mail' => 'Patvirtinti el. paštą',
    'Continue' => 'Tęsti',
    'Could not send confirmation email' => 'Nepavyko išsiųsti patvirtinimo laiško',
    'E-mail' => 'El. paštas',
    'E-mail confirmation for' => 'El. paštas patvirtinimui',
    'E-mail confirmed' => 'El. paštas patvirtintas',
    'E-mail is invalid' => 'Neteisingas el. paštas',
    'Forgot password ?' => 'Pamiršote slaptažodį?',
    'Incorrect username or password.' => 'Neteisingas vartotojo vardas arba slaptažodis',
    'Login' => 'Prisijungti',
    'Login has been taken' => 'Šis prisijungimo vardas užimtas',
    'Password' => 'Slaptažodis',
    'Password recovery' => 'Slaptažodžio atkūrimas',
    'Password reset for' => 'Slaptažodžio atkūrimas',
    'Recover' => 'Atkurti',
    'Register' => 'Registruotis',
    'Registration' => 'Registracija',
    'Registration - confirm your e-mail' => 'Registracija - patvirtinkite savo el. paštą',
    'Remember me' => 'Prisiminti mane',
    'Repeat password' => 'Pakartokite slaptažodį',
    'This E-mail already exists' => 'Šis el. pašto adresas jau egzistuoja',
    'Token not found. It may be expired' => 'Nepavyko rasti kodo. Galbūt jo galiojimas pasibaigė.',
    'Token not found. It may be expired. Try reset password once more' => 'Nepavyko rasti kodo. Galbūt jo galiojimas pasibaigė. Pabandykite pakeisti slaptažodį iš naujo',
    'Too many attempts' => 'Per daug bandymų',
    'Unable to send message for email provided' => 'Nepavyko išsiųsti el. laiško nurodytu adresu',
    'Username' => 'Prisijungimo vardas',
    'You could not login from this IP' => 'Jūs negalite prisijungti iš šio IP adreso',
    'Your email has not been confirmed yet.' => 'Jūs dar nepatvirtinote savo el. pašto adreso',
];
